INSERT INTO apa.sous_type_materiel (type_id, nom)
VALUES (1, 'Appareil photo argentique'),
       (1, 'Appareil photo numérique'),
       (1, 'Châssis'),
       (1, 'Objectif'),
       (1, 'Flash'),
       (1, 'Pied'),
       (1, 'Rotule'),
       (1, 'Déclencheur '),
       (1, 'Cellule'),
       (1, 'Filtre'),
       (1, 'Porte filtre'),
       (1, 'Adaptateur'),
       (1, 'Accessoire '),
       (2, 'Cuve'),
       (2, 'Châssis'),
       (2, 'Spirale'),
       (2, 'Accessoire'),
       (3, 'Agrandisseur'),
       (3, 'Objectifs'),
       (3, 'Accessoire');